/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author TOSHIBA
 */
public class JFFinal extends javax.swing.JFrame {

    /**
     * Creates new form JFFinal
     */
    public JFFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JlabelAccesosrios = new javax.swing.JLabel();
        JLabelPantalon = new javax.swing.JLabel();
        LabelCabello = new javax.swing.JLabel();
        LabelBarba = new javax.swing.JLabel();
        JLabelCamisa = new javax.swing.JLabel();
        LabelFunk1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BExportar = new javax.swing.JButton();
        BAntes = new javax.swing.JButton();
        TextName = new javax.swing.JTextField();
        BSetName = new javax.swing.JButton();
        JlabelNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(65, 96, 202));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(JlabelAccesosrios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 258, 112, 130));
        jPanel3.add(JLabelPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 220, 100, 199));
        jPanel3.add(LabelCabello, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 240, 118, 90));
        jPanel3.add(LabelBarba, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, 40));
        jPanel3.add(JLabelCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 275, 90, 105));

        LabelFunk1.setDoubleBuffered(true);
        jPanel3.add(LabelFunk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME YOUR POP!");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -30, 700, 700));

        BExportar.setBackground(new java.awt.Color(33, 137, 210));
        BExportar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BExportar.setForeground(new java.awt.Color(255, 255, 255));
        BExportar.setText("Export");
        BExportar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(BExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, 190, 40));

        BAntes.setBackground(new java.awt.Color(33, 137, 210));
        BAntes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BAntes.setForeground(new java.awt.Color(255, 255, 255));
        BAntes.setText("Back");
        BAntes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAntesActionPerformed(evt);
            }
        });
        jPanel3.add(BAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 190, 40));

        TextName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(TextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 350, 40));

        BSetName.setBackground(new java.awt.Color(33, 137, 210));
        BSetName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BSetName.setForeground(new java.awt.Color(255, 255, 255));
        BSetName.setText("Set name");
        BSetName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BSetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSetNameActionPerformed(evt);
            }
        });
        jPanel3.add(BSetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 120, -1));

        JlabelNombre.setEditable(false);
        JlabelNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(JlabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAntesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAntesActionPerformed

    private void BSetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSetNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BAntes;
    public javax.swing.JButton BExportar;
    public javax.swing.JButton BSetName;
    public javax.swing.JLabel JLabelCamisa;
    public javax.swing.JLabel JLabelPantalon;
    public javax.swing.JLabel JlabelAccesosrios;
    public javax.swing.JTextField JlabelNombre;
    public javax.swing.JLabel LabelBarba;
    public javax.swing.JLabel LabelCabello;
    public javax.swing.JLabel LabelFunk1;
    public javax.swing.JTextField TextName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
