/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;

/**
 *
 * @author Laura
 */
public class JFPaginaSiguiente extends javax.swing.JFrame {

    /**
     * Creates new form JFPaginaSiguiente
     */
    public JFPaginaSiguiente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelFunk1 = new javax.swing.JLabel();
        BMujer = new javax.swing.JButton();
        BHombre = new javax.swing.JButton();
        Bblanco = new javax.swing.JButton();
        Bblanco2 = new javax.swing.JButton();
        BNegro = new javax.swing.JButton();
        BNegro2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bantes = new javax.swing.JButton();
        Bsiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 800));

        jPanel1.setBackground(new java.awt.Color(65, 96, 202));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 707));

        LabelFunk1.setDoubleBuffered(true);

        BMujer.setBackground(new java.awt.Color(153, 204, 255));
        BMujer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BMujer.setForeground(new java.awt.Color(177, 207, 238));
        BMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SiluetaMujer.png"))); // NOI18N
        BMujer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BMujer.setBorderPainted(false);
        BMujer.setContentAreaFilled(false);
        BMujer.setPreferredSize(new java.awt.Dimension(200, 190));
        BMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMujerActionPerformed(evt);
            }
        });

        BHombre.setBackground(new java.awt.Color(153, 204, 255));
        BHombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BHombre.setForeground(new java.awt.Color(153, 204, 255));
        BHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SiluetaHombre.png"))); // NOI18N
        BHombre.setToolTipText("");
        BHombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BHombre.setBorderPainted(false);
        BHombre.setContentAreaFilled(false);
        BHombre.setHideActionText(true);
        BHombre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BHombre.setIconTextGap(6);
        BHombre.setPreferredSize(new java.awt.Dimension(200, 190));
        BHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHombreActionPerformed(evt);
            }
        });

        Bblanco.setBackground(new java.awt.Color(33, 137, 210));
        Bblanco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Bblanco.setForeground(new java.awt.Color(255, 255, 255));
        Bblanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color1.png"))); // NOI18N
        Bblanco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Bblanco.setContentAreaFilled(false);
        Bblanco.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color1.png"))); // NOI18N
        Bblanco.setEnabled(false);
        Bblanco.setMaximumSize(new java.awt.Dimension(106, 108));
        Bblanco.setMinimumSize(new java.awt.Dimension(106, 108));
        Bblanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BblancoActionPerformed(evt);
            }
        });

        Bblanco2.setBackground(new java.awt.Color(33, 137, 210));
        Bblanco2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Bblanco2.setForeground(new java.awt.Color(255, 255, 255));
        Bblanco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color2.png"))); // NOI18N
        Bblanco2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Bblanco2.setBorderPainted(false);
        Bblanco2.setContentAreaFilled(false);
        Bblanco2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color2.png"))); // NOI18N
        Bblanco2.setEnabled(false);
        Bblanco2.setMaximumSize(new java.awt.Dimension(106, 108));
        Bblanco2.setMinimumSize(new java.awt.Dimension(106, 108));
        Bblanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bblanco2ActionPerformed(evt);
            }
        });

        BNegro.setBackground(new java.awt.Color(33, 137, 210));
        BNegro.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BNegro.setForeground(new java.awt.Color(255, 255, 255));
        BNegro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color3.png"))); // NOI18N
        BNegro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BNegro.setContentAreaFilled(false);
        BNegro.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color3.png"))); // NOI18N
        BNegro.setEnabled(false);
        BNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNegroActionPerformed(evt);
            }
        });

        BNegro2.setBackground(new java.awt.Color(33, 137, 210));
        BNegro2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BNegro2.setForeground(new java.awt.Color(255, 255, 255));
        BNegro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color4.png"))); // NOI18N
        BNegro2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BNegro2.setContentAreaFilled(false);
        BNegro2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Color4.png"))); // NOI18N
        BNegro2.setEnabled(false);
        BNegro2.setMaximumSize(new java.awt.Dimension(106, 108));
        BNegro2.setMinimumSize(new java.awt.Dimension(106, 108));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GETTING STARTED");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose first your body type & then your skin color!");

        Bantes.setBackground(new java.awt.Color(33, 137, 210));
        Bantes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Bantes.setForeground(new java.awt.Color(255, 255, 255));
        Bantes.setText("Back");
        Bantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantesActionPerformed(evt);
            }
        });

        Bsiguiente.setBackground(new java.awt.Color(33, 137, 210));
        Bsiguiente.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Bsiguiente.setForeground(new java.awt.Color(255, 255, 255));
        Bsiguiente.setText("Continue");
        Bsiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bsiguiente.setEnabled(false);
        Bsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Bblanco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bblanco2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BNegro2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Bantes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelFunk1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(LabelFunk1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNegro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BNegro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bblanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bblanco2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMujer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNegroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNegroActionPerformed

    private void BblancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BblancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BblancoActionPerformed

    private void Bblanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bblanco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bblanco2ActionPerformed

    private void BHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHombreActionPerformed

    private void BMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BMujerActionPerformed

    private void BantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BantesActionPerformed

    private void BsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPaginaSiguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPaginaSiguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPaginaSiguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPaginaSiguiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPaginaSiguiente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BHombre;
    public javax.swing.JButton BMujer;
    public javax.swing.JButton BNegro;
    public javax.swing.JButton BNegro2;
    public javax.swing.JButton Bantes;
    public javax.swing.JButton Bblanco;
    public javax.swing.JButton Bblanco2;
    public javax.swing.JButton Bsiguiente;
    public javax.swing.JLabel LabelFunk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
